"""
test_code_reviewer.py — put this in backend/ (same level as main.py)

Run with:  python -m test_code_reviewer

This is your actual "code reviewer" in action:
1. You give it a real GitHub URL OR a real ZIP file on your computer
2. It downloads/extracts and indexes the code (Repository RAG)
3. You ask it as many real questions as you want
4. Each answer is generated by Groq, grounded in the ACTUAL code

Type 'quit' at any question prompt to stop and clean up.
"""

import os
from dotenv import load_dotenv
load_dotenv()

from app.core.rag.github_fetch import download_github_repo, extract_uploaded_zip, cleanup_repo
from app.core.rag.repository_rag import ingest_repository
from app.core.rag.generate import ask_about_repo

REPO_ID = "manual-review-session"

print("=" * 60)
print("Aaroh AI — Code Reviewer")
print("=" * 60)

source_type = input("\nGitHub URL or local ZIP path? Type 'github' or 'zip': ").strip().lower()

if source_type == "github":
    repo_url = input("Paste the GitHub URL (e.g. https://github.com/owner/repo): ").strip()
    print(f"\nDownloading {repo_url} ...")
    local_path = download_github_repo(repo_url)
    is_temp = True

elif source_type == "zip":
    zip_path = input("Paste the full path to your .zip file: ").strip().strip('"')
    if not os.path.exists(zip_path):
        print(f"File not found: {zip_path}")
        exit(1)
    print(f"\nExtracting {zip_path} ...")
    local_path = extract_uploaded_zip(zip_path)
    is_temp = True

else:
    print("Please type 'github' or 'zip'.")
    exit(1)

print(f"Extracted to: {local_path}")
print("\nIndexing the code (this may take a minute for a large repo)...")
ingest_repository(local_path, REPO_ID)

print("\n" + "=" * 60)
print("Ready. Ask anything about this codebase.")
print("Examples: 'review my authentication logic', 'is this code secure',")
print("'explain how the main entry point works', 'find potential bugs'")
print("=" * 60)

while True:
    question = input("\nYour question (or 'quit' to stop): ").strip()
    if question.lower() in ("quit", "exit", "q"):
        break
    if not question:
        continue

    print("\nThinking...\n")
    result = ask_about_repo(question, REPO_ID)

    print("-" * 60)
    print(result["answer"])
    print("-" * 60)
    print(f"Sources used: {', '.join(result['sources']) if result['sources'] else 'none'}")

if is_temp:
    cleanup_repo(local_path)
print("\nCleaned up. Session ended.")