"""
app/core/agents/pdf_generator.py

Generates a downloadable PDF version of the Project Health Report —
matches the "AI Project Health Report" page shown in the frontend
(Executive Summary, overall score, 6 category breakdown).

Uses WeasyPrint to render an HTML template into a PDF. No new LLM
call here — this consumes the already-generated report data from
generate_project_report(), same as the PDF Report page does.
"""

import os
from datetime import datetime
from weasyprint import HTML

from app.core.rag.report_generator import generate_project_report

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated_reports")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def _score_label(score: float) -> str:
    if score >= 85:
        return "Excellent"
    elif score >= 70:
        return "Good"
    elif score >= 50:
        return "Needs Improvement"
    return "Critical"


def _build_html(project_name: str, report: dict) -> str:
    categories = {
        "Architecture": report.get("architecture_score", 0),
        "Scalability": report.get("scalability_score", 0),
        "Documentation": report.get("documentation_score", 0),
        "Deployment Readiness": report.get("deployment_readiness_score", 0),
        "Code Quality": report.get("code_quality_score", 0),
        "Security": report.get("security_score", 0),
        "Performance": report.get("performance_score", 0),
    }
    categories = {k: v for k, v in categories.items() if v is not None}

    overall_score = round(sum(categories.values()) / len(categories), 1) if categories else 0
    overall_label = _score_label(overall_score)
    generated_date = datetime.now().strftime("%-m/%-d/%Y")

    rows = "".join(
        f"""
        <tr>
            <td class="cat-name">{name}</td>
            <td class="cat-score">{score}/100</td>
            <td class="cat-bar-cell">
                <div class="bar-track"><div class="bar-fill" style="width:{score}%"></div></div>
            </td>
        </tr>
        """
        for name, score in categories.items()
    )

    return f"""
    <html>
    <head>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; padding: 40px; }}
        .header {{ text-align: center; margin-bottom: 30px; }}
        .logo {{ font-size: 28px; font-weight: bold; color: #2563eb; }}
        h1 {{ font-size: 22px; margin: 10px 0 4px; }}
        .subtitle {{ color: #555; margin-bottom: 4px; }}
        .meta {{ font-size: 12px; color: #888; margin-bottom: 20px; }}
        .summary-box {{ display: flex; gap: 20px; border: 1px solid #e5e7eb; border-radius: 10px; padding: 20px; margin-bottom: 24px; }}
        .score-circle {{ text-align: center; min-width: 120px; }}
        .score-number {{ font-size: 40px; font-weight: bold; color: #16a34a; }}
        .score-caption {{ font-size: 12px; color: #666; }}
        .score-status {{ font-size: 13px; font-weight: 600; color: #16a34a; }}
        .summary-text {{ font-size: 13px; line-height: 1.6; color: #333; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        td {{ padding: 10px 6px; border-bottom: 1px solid #eee; font-size: 13px; vertical-align: middle; }}
        .cat-name {{ width: 30%; font-weight: 600; }}
        .cat-score {{ width: 15%; color: #444; }}
        .bar-track {{ background: #eee; border-radius: 6px; height: 10px; width: 100%; overflow: hidden; }}
        .bar-fill {{ background: #2563eb; height: 100%; }}
        .footer {{ text-align: center; font-size: 11px; color: #999; margin-top: 30px; }}
    </style>
    </head>
    <body>
        <div class="header">
            <div class="logo">⚡ Aaroh AI</div>
            <h1>AI Project Health Report</h1>
            <div class="subtitle">{project_name}</div>
            <div class="meta">Generated: {generated_date} &nbsp;|&nbsp; Powered by Aaroh AI</div>
        </div>

        <div class="summary-box">
            <div class="score-circle">
                <div class="score-number">{overall_score}</div>
                <div class="score-caption">Overall Health Score</div>
                <div class="score-status">{overall_label}</div>
            </div>
            <div class="summary-text">
                <strong>Executive Summary</strong><br/>
                {report.get("ai_commentary", "No commentary available.")}
            </div>
        </div>

        <table>
            <tr><th style="text-align:left; font-size:13px;">Category</th><th></th><th></th></tr>
            {rows}
        </table>

        <div class="footer">Generated by Aaroh AI &mdash; automated analysis, review before relying on it for decisions.</div>
    </body>
    </html>
    """


def generate_pdf_report(repo_id: str, project_name: str = "Untitled Project") -> str:
    """
    Generates a PDF health report and saves it to disk.
    Returns the absolute file path of the generated PDF.
    """
    report = generate_project_report(repo_id)
    html_content = _build_html(project_name, report)

    filename = f"health_report_{repo_id}.pdf"
    output_path = os.path.join(OUTPUT_DIR, filename)

    HTML(string=html_content).write_pdf(output_path)
    return output_path